// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli

import (
	"context"
	"github.com/avitsrimer/jcli/internal/jenkins"
	"sync"
)

// Ensure, that jenkinsClientMock does implement jenkinsClient.
// If this is not the case, regenerate this file with moq.
var _ jenkinsClient = &jenkinsClientMock{}

// jenkinsClientMock is a mock implementation of jenkinsClient.
//
//	func TestSomethingThatUsesjenkinsClient(t *testing.T) {
//
//		// make and configure a mocked jenkinsClient
//		mockedjenkinsClient := &jenkinsClientMock{
//			BuildFunc: func(ctx context.Context, jobPath string, params map[string]string) (string, error) {
//				panic("mock out the Build method")
//			},
//			BuildParamsFunc: func(ctx context.Context, buildURL string) ([]jenkins.BuildParam, error) {
//				panic("mock out the BuildParams method")
//			},
//			BuildResultFunc: func(ctx context.Context, buildURL string) (jenkins.BuildResult, error) {
//				panic("mock out the BuildResult method")
//			},
//			BuildStatusFunc: func(ctx context.Context, buildURL string) (jenkins.Build, error) {
//				panic("mock out the BuildStatus method")
//			},
//			BuildsFunc: func(ctx context.Context, jobPath string, limit int) ([]jenkins.Build, error) {
//				panic("mock out the Builds method")
//			},
//			ConsoleProgressiveFunc: func(ctx context.Context, buildURL string, start int64) (jenkins.ConsoleChunk, error) {
//				panic("mock out the ConsoleProgressive method")
//			},
//			ConsoleTextFunc: func(ctx context.Context, buildURL string) (string, error) {
//				panic("mock out the ConsoleText method")
//			},
//			JobParamsFunc: func(ctx context.Context, jobPath string) ([]jenkins.Param, error) {
//				panic("mock out the JobParams method")
//			},
//			JobsFunc: func(ctx context.Context) ([]jenkins.Job, error) {
//				panic("mock out the Jobs method")
//			},
//			LastBuildFunc: func(ctx context.Context, jobPath string) (jenkins.Build, bool, error) {
//				panic("mock out the LastBuild method")
//			},
//			QueueItemFunc: func(ctx context.Context, queueURL string) (jenkins.QueueItem, error) {
//				panic("mock out the QueueItem method")
//			},
//			RunningBuildsFunc: func(ctx context.Context) ([]jenkins.RunningBuild, error) {
//				panic("mock out the RunningBuilds method")
//			},
//			StageViewFunc: func(ctx context.Context, buildURL string) ([]jenkins.Stage, error) {
//				panic("mock out the StageView method")
//			},
//			StopFunc: func(ctx context.Context, buildURL string) error {
//				panic("mock out the Stop method")
//			},
//			WhoAmIFunc: func(ctx context.Context) (jenkins.Identity, error) {
//				panic("mock out the WhoAmI method")
//			},
//		}
//
//		// use mockedjenkinsClient in code that requires jenkinsClient
//		// and then make assertions.
//
//	}
type jenkinsClientMock struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(ctx context.Context, jobPath string, params map[string]string) (string, error)

	// BuildParamsFunc mocks the BuildParams method.
	BuildParamsFunc func(ctx context.Context, buildURL string) ([]jenkins.BuildParam, error)

	// BuildResultFunc mocks the BuildResult method.
	BuildResultFunc func(ctx context.Context, buildURL string) (jenkins.BuildResult, error)

	// BuildStatusFunc mocks the BuildStatus method.
	BuildStatusFunc func(ctx context.Context, buildURL string) (jenkins.Build, error)

	// BuildsFunc mocks the Builds method.
	BuildsFunc func(ctx context.Context, jobPath string, limit int) ([]jenkins.Build, error)

	// ConsoleProgressiveFunc mocks the ConsoleProgressive method.
	ConsoleProgressiveFunc func(ctx context.Context, buildURL string, start int64) (jenkins.ConsoleChunk, error)

	// ConsoleTextFunc mocks the ConsoleText method.
	ConsoleTextFunc func(ctx context.Context, buildURL string) (string, error)

	// JobParamsFunc mocks the JobParams method.
	JobParamsFunc func(ctx context.Context, jobPath string) ([]jenkins.Param, error)

	// JobsFunc mocks the Jobs method.
	JobsFunc func(ctx context.Context) ([]jenkins.Job, error)

	// LastBuildFunc mocks the LastBuild method.
	LastBuildFunc func(ctx context.Context, jobPath string) (jenkins.Build, bool, error)

	// QueueItemFunc mocks the QueueItem method.
	QueueItemFunc func(ctx context.Context, queueURL string) (jenkins.QueueItem, error)

	// RunningBuildsFunc mocks the RunningBuilds method.
	RunningBuildsFunc func(ctx context.Context) ([]jenkins.RunningBuild, error)

	// StageViewFunc mocks the StageView method.
	StageViewFunc func(ctx context.Context, buildURL string) ([]jenkins.Stage, error)

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, buildURL string) error

	// WhoAmIFunc mocks the WhoAmI method.
	WhoAmIFunc func(ctx context.Context) (jenkins.Identity, error)

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
			// Params is the params argument value.
			Params map[string]string
		}
		// BuildParams holds details about calls to the BuildParams method.
		BuildParams []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// BuildResult holds details about calls to the BuildResult method.
		BuildResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// BuildStatus holds details about calls to the BuildStatus method.
		BuildStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// Builds holds details about calls to the Builds method.
		Builds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
			// Limit is the limit argument value.
			Limit int
		}
		// ConsoleProgressive holds details about calls to the ConsoleProgressive method.
		ConsoleProgressive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
			// Start is the start argument value.
			Start int64
		}
		// ConsoleText holds details about calls to the ConsoleText method.
		ConsoleText []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// JobParams holds details about calls to the JobParams method.
		JobParams []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
		}
		// Jobs holds details about calls to the Jobs method.
		Jobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// LastBuild holds details about calls to the LastBuild method.
		LastBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
		}
		// QueueItem holds details about calls to the QueueItem method.
		QueueItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueueURL is the queueURL argument value.
			QueueURL string
		}
		// RunningBuilds holds details about calls to the RunningBuilds method.
		RunningBuilds []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// StageView holds details about calls to the StageView method.
		StageView []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// WhoAmI holds details about calls to the WhoAmI method.
		WhoAmI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockBuild              sync.RWMutex
	lockBuildParams        sync.RWMutex
	lockBuildResult        sync.RWMutex
	lockBuildStatus        sync.RWMutex
	lockBuilds             sync.RWMutex
	lockConsoleProgressive sync.RWMutex
	lockConsoleText        sync.RWMutex
	lockJobParams          sync.RWMutex
	lockJobs               sync.RWMutex
	lockLastBuild          sync.RWMutex
	lockQueueItem          sync.RWMutex
	lockRunningBuilds      sync.RWMutex
	lockStageView          sync.RWMutex
	lockStop               sync.RWMutex
	lockWhoAmI             sync.RWMutex
}

// Build calls BuildFunc.
func (mock *jenkinsClientMock) Build(ctx context.Context, jobPath string, params map[string]string) (string, error) {
	if mock.BuildFunc == nil {
		panic("jenkinsClientMock.BuildFunc: method is nil but jenkinsClient.Build was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
		Params  map[string]string
	}{
		Ctx:     ctx,
		JobPath: jobPath,
		Params:  params,
	}
	mock.lockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	mock.lockBuild.Unlock()
	return mock.BuildFunc(ctx, jobPath, params)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildCalls())
func (mock *jenkinsClientMock) BuildCalls() []struct {
	Ctx     context.Context
	JobPath string
	Params  map[string]string
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
		Params  map[string]string
	}
	mock.lockBuild.RLock()
	calls = mock.calls.Build
	mock.lockBuild.RUnlock()
	return calls
}

// BuildParams calls BuildParamsFunc.
func (mock *jenkinsClientMock) BuildParams(ctx context.Context, buildURL string) ([]jenkins.BuildParam, error) {
	if mock.BuildParamsFunc == nil {
		panic("jenkinsClientMock.BuildParamsFunc: method is nil but jenkinsClient.BuildParams was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockBuildParams.Lock()
	mock.calls.BuildParams = append(mock.calls.BuildParams, callInfo)
	mock.lockBuildParams.Unlock()
	return mock.BuildParamsFunc(ctx, buildURL)
}

// BuildParamsCalls gets all the calls that were made to BuildParams.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildParamsCalls())
func (mock *jenkinsClientMock) BuildParamsCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockBuildParams.RLock()
	calls = mock.calls.BuildParams
	mock.lockBuildParams.RUnlock()
	return calls
}

// BuildResult calls BuildResultFunc.
func (mock *jenkinsClientMock) BuildResult(ctx context.Context, buildURL string) (jenkins.BuildResult, error) {
	if mock.BuildResultFunc == nil {
		panic("jenkinsClientMock.BuildResultFunc: method is nil but jenkinsClient.BuildResult was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockBuildResult.Lock()
	mock.calls.BuildResult = append(mock.calls.BuildResult, callInfo)
	mock.lockBuildResult.Unlock()
	return mock.BuildResultFunc(ctx, buildURL)
}

// BuildResultCalls gets all the calls that were made to BuildResult.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildResultCalls())
func (mock *jenkinsClientMock) BuildResultCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockBuildResult.RLock()
	calls = mock.calls.BuildResult
	mock.lockBuildResult.RUnlock()
	return calls
}

// BuildStatus calls BuildStatusFunc.
func (mock *jenkinsClientMock) BuildStatus(ctx context.Context, buildURL string) (jenkins.Build, error) {
	if mock.BuildStatusFunc == nil {
		panic("jenkinsClientMock.BuildStatusFunc: method is nil but jenkinsClient.BuildStatus was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockBuildStatus.Lock()
	mock.calls.BuildStatus = append(mock.calls.BuildStatus, callInfo)
	mock.lockBuildStatus.Unlock()
	return mock.BuildStatusFunc(ctx, buildURL)
}

// BuildStatusCalls gets all the calls that were made to BuildStatus.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildStatusCalls())
func (mock *jenkinsClientMock) BuildStatusCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockBuildStatus.RLock()
	calls = mock.calls.BuildStatus
	mock.lockBuildStatus.RUnlock()
	return calls
}

// Builds calls BuildsFunc.
func (mock *jenkinsClientMock) Builds(ctx context.Context, jobPath string, limit int) ([]jenkins.Build, error) {
	if mock.BuildsFunc == nil {
		panic("jenkinsClientMock.BuildsFunc: method is nil but jenkinsClient.Builds was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
		Limit   int
	}{
		Ctx:     ctx,
		JobPath: jobPath,
		Limit:   limit,
	}
	mock.lockBuilds.Lock()
	mock.calls.Builds = append(mock.calls.Builds, callInfo)
	mock.lockBuilds.Unlock()
	return mock.BuildsFunc(ctx, jobPath, limit)
}

// BuildsCalls gets all the calls that were made to Builds.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildsCalls())
func (mock *jenkinsClientMock) BuildsCalls() []struct {
	Ctx     context.Context
	JobPath string
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
		Limit   int
	}
	mock.lockBuilds.RLock()
	calls = mock.calls.Builds
	mock.lockBuilds.RUnlock()
	return calls
}

// ConsoleProgressive calls ConsoleProgressiveFunc.
func (mock *jenkinsClientMock) ConsoleProgressive(ctx context.Context, buildURL string, start int64) (jenkins.ConsoleChunk, error) {
	if mock.ConsoleProgressiveFunc == nil {
		panic("jenkinsClientMock.ConsoleProgressiveFunc: method is nil but jenkinsClient.ConsoleProgressive was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
		Start    int64
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
		Start:    start,
	}
	mock.lockConsoleProgressive.Lock()
	mock.calls.ConsoleProgressive = append(mock.calls.ConsoleProgressive, callInfo)
	mock.lockConsoleProgressive.Unlock()
	return mock.ConsoleProgressiveFunc(ctx, buildURL, start)
}

// ConsoleProgressiveCalls gets all the calls that were made to ConsoleProgressive.
// Check the length with:
//
//	len(mockedjenkinsClient.ConsoleProgressiveCalls())
func (mock *jenkinsClientMock) ConsoleProgressiveCalls() []struct {
	Ctx      context.Context
	BuildURL string
	Start    int64
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
		Start    int64
	}
	mock.lockConsoleProgressive.RLock()
	calls = mock.calls.ConsoleProgressive
	mock.lockConsoleProgressive.RUnlock()
	return calls
}

// ConsoleText calls ConsoleTextFunc.
func (mock *jenkinsClientMock) ConsoleText(ctx context.Context, buildURL string) (string, error) {
	if mock.ConsoleTextFunc == nil {
		panic("jenkinsClientMock.ConsoleTextFunc: method is nil but jenkinsClient.ConsoleText was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockConsoleText.Lock()
	mock.calls.ConsoleText = append(mock.calls.ConsoleText, callInfo)
	mock.lockConsoleText.Unlock()
	return mock.ConsoleTextFunc(ctx, buildURL)
}

// ConsoleTextCalls gets all the calls that were made to ConsoleText.
// Check the length with:
//
//	len(mockedjenkinsClient.ConsoleTextCalls())
func (mock *jenkinsClientMock) ConsoleTextCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockConsoleText.RLock()
	calls = mock.calls.ConsoleText
	mock.lockConsoleText.RUnlock()
	return calls
}

// JobParams calls JobParamsFunc.
func (mock *jenkinsClientMock) JobParams(ctx context.Context, jobPath string) ([]jenkins.Param, error) {
	if mock.JobParamsFunc == nil {
		panic("jenkinsClientMock.JobParamsFunc: method is nil but jenkinsClient.JobParams was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
	}{
		Ctx:     ctx,
		JobPath: jobPath,
	}
	mock.lockJobParams.Lock()
	mock.calls.JobParams = append(mock.calls.JobParams, callInfo)
	mock.lockJobParams.Unlock()
	return mock.JobParamsFunc(ctx, jobPath)
}

// JobParamsCalls gets all the calls that were made to JobParams.
// Check the length with:
//
//	len(mockedjenkinsClient.JobParamsCalls())
func (mock *jenkinsClientMock) JobParamsCalls() []struct {
	Ctx     context.Context
	JobPath string
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
	}
	mock.lockJobParams.RLock()
	calls = mock.calls.JobParams
	mock.lockJobParams.RUnlock()
	return calls
}

// Jobs calls JobsFunc.
func (mock *jenkinsClientMock) Jobs(ctx context.Context) ([]jenkins.Job, error) {
	if mock.JobsFunc == nil {
		panic("jenkinsClientMock.JobsFunc: method is nil but jenkinsClient.Jobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockJobs.Lock()
	mock.calls.Jobs = append(mock.calls.Jobs, callInfo)
	mock.lockJobs.Unlock()
	return mock.JobsFunc(ctx)
}

// JobsCalls gets all the calls that were made to Jobs.
// Check the length with:
//
//	len(mockedjenkinsClient.JobsCalls())
func (mock *jenkinsClientMock) JobsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockJobs.RLock()
	calls = mock.calls.Jobs
	mock.lockJobs.RUnlock()
	return calls
}

// LastBuild calls LastBuildFunc.
func (mock *jenkinsClientMock) LastBuild(ctx context.Context, jobPath string) (jenkins.Build, bool, error) {
	if mock.LastBuildFunc == nil {
		panic("jenkinsClientMock.LastBuildFunc: method is nil but jenkinsClient.LastBuild was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
	}{
		Ctx:     ctx,
		JobPath: jobPath,
	}
	mock.lockLastBuild.Lock()
	mock.calls.LastBuild = append(mock.calls.LastBuild, callInfo)
	mock.lockLastBuild.Unlock()
	return mock.LastBuildFunc(ctx, jobPath)
}

// LastBuildCalls gets all the calls that were made to LastBuild.
// Check the length with:
//
//	len(mockedjenkinsClient.LastBuildCalls())
func (mock *jenkinsClientMock) LastBuildCalls() []struct {
	Ctx     context.Context
	JobPath string
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
	}
	mock.lockLastBuild.RLock()
	calls = mock.calls.LastBuild
	mock.lockLastBuild.RUnlock()
	return calls
}

// QueueItem calls QueueItemFunc.
func (mock *jenkinsClientMock) QueueItem(ctx context.Context, queueURL string) (jenkins.QueueItem, error) {
	if mock.QueueItemFunc == nil {
		panic("jenkinsClientMock.QueueItemFunc: method is nil but jenkinsClient.QueueItem was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		QueueURL string
	}{
		Ctx:      ctx,
		QueueURL: queueURL,
	}
	mock.lockQueueItem.Lock()
	mock.calls.QueueItem = append(mock.calls.QueueItem, callInfo)
	mock.lockQueueItem.Unlock()
	return mock.QueueItemFunc(ctx, queueURL)
}

// QueueItemCalls gets all the calls that were made to QueueItem.
// Check the length with:
//
//	len(mockedjenkinsClient.QueueItemCalls())
func (mock *jenkinsClientMock) QueueItemCalls() []struct {
	Ctx      context.Context
	QueueURL string
} {
	var calls []struct {
		Ctx      context.Context
		QueueURL string
	}
	mock.lockQueueItem.RLock()
	calls = mock.calls.QueueItem
	mock.lockQueueItem.RUnlock()
	return calls
}

// RunningBuilds calls RunningBuildsFunc.
func (mock *jenkinsClientMock) RunningBuilds(ctx context.Context) ([]jenkins.RunningBuild, error) {
	if mock.RunningBuildsFunc == nil {
		panic("jenkinsClientMock.RunningBuildsFunc: method is nil but jenkinsClient.RunningBuilds was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRunningBuilds.Lock()
	mock.calls.RunningBuilds = append(mock.calls.RunningBuilds, callInfo)
	mock.lockRunningBuilds.Unlock()
	return mock.RunningBuildsFunc(ctx)
}

// RunningBuildsCalls gets all the calls that were made to RunningBuilds.
// Check the length with:
//
//	len(mockedjenkinsClient.RunningBuildsCalls())
func (mock *jenkinsClientMock) RunningBuildsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRunningBuilds.RLock()
	calls = mock.calls.RunningBuilds
	mock.lockRunningBuilds.RUnlock()
	return calls
}

// StageView calls StageViewFunc.
func (mock *jenkinsClientMock) StageView(ctx context.Context, buildURL string) ([]jenkins.Stage, error) {
	if mock.StageViewFunc == nil {
		panic("jenkinsClientMock.StageViewFunc: method is nil but jenkinsClient.StageView was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockStageView.Lock()
	mock.calls.StageView = append(mock.calls.StageView, callInfo)
	mock.lockStageView.Unlock()
	return mock.StageViewFunc(ctx, buildURL)
}

// StageViewCalls gets all the calls that were made to StageView.
// Check the length with:
//
//	len(mockedjenkinsClient.StageViewCalls())
func (mock *jenkinsClientMock) StageViewCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockStageView.RLock()
	calls = mock.calls.StageView
	mock.lockStageView.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *jenkinsClientMock) Stop(ctx context.Context, buildURL string) error {
	if mock.StopFunc == nil {
		panic("jenkinsClientMock.StopFunc: method is nil but jenkinsClient.Stop was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(ctx, buildURL)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedjenkinsClient.StopCalls())
func (mock *jenkinsClientMock) StopCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// WhoAmI calls WhoAmIFunc.
func (mock *jenkinsClientMock) WhoAmI(ctx context.Context) (jenkins.Identity, error) {
	if mock.WhoAmIFunc == nil {
		panic("jenkinsClientMock.WhoAmIFunc: method is nil but jenkinsClient.WhoAmI was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWhoAmI.Lock()
	mock.calls.WhoAmI = append(mock.calls.WhoAmI, callInfo)
	mock.lockWhoAmI.Unlock()
	return mock.WhoAmIFunc(ctx)
}

// WhoAmICalls gets all the calls that were made to WhoAmI.
// Check the length with:
//
//	len(mockedjenkinsClient.WhoAmICalls())
func (mock *jenkinsClientMock) WhoAmICalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWhoAmI.RLock()
	calls = mock.calls.WhoAmI
	mock.lockWhoAmI.RUnlock()
	return calls
}
