// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli

import (
	"context"
	"github.com/avitsrimer/jcli/internal/jenkins"
	"sync"
)

// Ensure, that jenkinsClientMock does implement jenkinsClient.
// If this is not the case, regenerate this file with moq.
var _ jenkinsClient = &jenkinsClientMock{}

// jenkinsClientMock is a mock implementation of jenkinsClient.
//
//	func TestSomethingThatUsesjenkinsClient(t *testing.T) {
//
//		// make and configure a mocked jenkinsClient
//		mockedjenkinsClient := &jenkinsClientMock{
//			BuildFunc: func(ctx context.Context, jobPath string, params map[string]string) (string, error) {
//				panic("mock out the Build method")
//			},
//			BuildResultFunc: func(ctx context.Context, buildURL string) (jenkins.BuildResult, error) {
//				panic("mock out the BuildResult method")
//			},
//			JobParamsFunc: func(ctx context.Context, jobPath string) ([]jenkins.Param, error) {
//				panic("mock out the JobParams method")
//			},
//			JobsFunc: func(ctx context.Context) ([]jenkins.Job, error) {
//				panic("mock out the Jobs method")
//			},
//			QueueItemFunc: func(ctx context.Context, queueURL string) (jenkins.QueueItem, error) {
//				panic("mock out the QueueItem method")
//			},
//			StageViewFunc: func(ctx context.Context, buildURL string) ([]jenkins.Stage, error) {
//				panic("mock out the StageView method")
//			},
//			WhoAmIFunc: func(ctx context.Context) (jenkins.Identity, error) {
//				panic("mock out the WhoAmI method")
//			},
//		}
//
//		// use mockedjenkinsClient in code that requires jenkinsClient
//		// and then make assertions.
//
//	}
type jenkinsClientMock struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(ctx context.Context, jobPath string, params map[string]string) (string, error)

	// BuildResultFunc mocks the BuildResult method.
	BuildResultFunc func(ctx context.Context, buildURL string) (jenkins.BuildResult, error)

	// JobParamsFunc mocks the JobParams method.
	JobParamsFunc func(ctx context.Context, jobPath string) ([]jenkins.Param, error)

	// JobsFunc mocks the Jobs method.
	JobsFunc func(ctx context.Context) ([]jenkins.Job, error)

	// QueueItemFunc mocks the QueueItem method.
	QueueItemFunc func(ctx context.Context, queueURL string) (jenkins.QueueItem, error)

	// StageViewFunc mocks the StageView method.
	StageViewFunc func(ctx context.Context, buildURL string) ([]jenkins.Stage, error)

	// WhoAmIFunc mocks the WhoAmI method.
	WhoAmIFunc func(ctx context.Context) (jenkins.Identity, error)

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
			// Params is the params argument value.
			Params map[string]string
		}
		// BuildResult holds details about calls to the BuildResult method.
		BuildResult []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// JobParams holds details about calls to the JobParams method.
		JobParams []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobPath is the jobPath argument value.
			JobPath string
		}
		// Jobs holds details about calls to the Jobs method.
		Jobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// QueueItem holds details about calls to the QueueItem method.
		QueueItem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueueURL is the queueURL argument value.
			QueueURL string
		}
		// StageView holds details about calls to the StageView method.
		StageView []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BuildURL is the buildURL argument value.
			BuildURL string
		}
		// WhoAmI holds details about calls to the WhoAmI method.
		WhoAmI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockBuild       sync.RWMutex
	lockBuildResult sync.RWMutex
	lockJobParams   sync.RWMutex
	lockJobs        sync.RWMutex
	lockQueueItem   sync.RWMutex
	lockStageView   sync.RWMutex
	lockWhoAmI      sync.RWMutex
}

// Build calls BuildFunc.
func (mock *jenkinsClientMock) Build(ctx context.Context, jobPath string, params map[string]string) (string, error) {
	if mock.BuildFunc == nil {
		panic("jenkinsClientMock.BuildFunc: method is nil but jenkinsClient.Build was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
		Params  map[string]string
	}{
		Ctx:     ctx,
		JobPath: jobPath,
		Params:  params,
	}
	mock.lockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	mock.lockBuild.Unlock()
	return mock.BuildFunc(ctx, jobPath, params)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildCalls())
func (mock *jenkinsClientMock) BuildCalls() []struct {
	Ctx     context.Context
	JobPath string
	Params  map[string]string
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
		Params  map[string]string
	}
	mock.lockBuild.RLock()
	calls = mock.calls.Build
	mock.lockBuild.RUnlock()
	return calls
}

// BuildResult calls BuildResultFunc.
func (mock *jenkinsClientMock) BuildResult(ctx context.Context, buildURL string) (jenkins.BuildResult, error) {
	if mock.BuildResultFunc == nil {
		panic("jenkinsClientMock.BuildResultFunc: method is nil but jenkinsClient.BuildResult was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockBuildResult.Lock()
	mock.calls.BuildResult = append(mock.calls.BuildResult, callInfo)
	mock.lockBuildResult.Unlock()
	return mock.BuildResultFunc(ctx, buildURL)
}

// BuildResultCalls gets all the calls that were made to BuildResult.
// Check the length with:
//
//	len(mockedjenkinsClient.BuildResultCalls())
func (mock *jenkinsClientMock) BuildResultCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockBuildResult.RLock()
	calls = mock.calls.BuildResult
	mock.lockBuildResult.RUnlock()
	return calls
}

// JobParams calls JobParamsFunc.
func (mock *jenkinsClientMock) JobParams(ctx context.Context, jobPath string) ([]jenkins.Param, error) {
	if mock.JobParamsFunc == nil {
		panic("jenkinsClientMock.JobParamsFunc: method is nil but jenkinsClient.JobParams was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		JobPath string
	}{
		Ctx:     ctx,
		JobPath: jobPath,
	}
	mock.lockJobParams.Lock()
	mock.calls.JobParams = append(mock.calls.JobParams, callInfo)
	mock.lockJobParams.Unlock()
	return mock.JobParamsFunc(ctx, jobPath)
}

// JobParamsCalls gets all the calls that were made to JobParams.
// Check the length with:
//
//	len(mockedjenkinsClient.JobParamsCalls())
func (mock *jenkinsClientMock) JobParamsCalls() []struct {
	Ctx     context.Context
	JobPath string
} {
	var calls []struct {
		Ctx     context.Context
		JobPath string
	}
	mock.lockJobParams.RLock()
	calls = mock.calls.JobParams
	mock.lockJobParams.RUnlock()
	return calls
}

// Jobs calls JobsFunc.
func (mock *jenkinsClientMock) Jobs(ctx context.Context) ([]jenkins.Job, error) {
	if mock.JobsFunc == nil {
		panic("jenkinsClientMock.JobsFunc: method is nil but jenkinsClient.Jobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockJobs.Lock()
	mock.calls.Jobs = append(mock.calls.Jobs, callInfo)
	mock.lockJobs.Unlock()
	return mock.JobsFunc(ctx)
}

// JobsCalls gets all the calls that were made to Jobs.
// Check the length with:
//
//	len(mockedjenkinsClient.JobsCalls())
func (mock *jenkinsClientMock) JobsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockJobs.RLock()
	calls = mock.calls.Jobs
	mock.lockJobs.RUnlock()
	return calls
}

// QueueItem calls QueueItemFunc.
func (mock *jenkinsClientMock) QueueItem(ctx context.Context, queueURL string) (jenkins.QueueItem, error) {
	if mock.QueueItemFunc == nil {
		panic("jenkinsClientMock.QueueItemFunc: method is nil but jenkinsClient.QueueItem was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		QueueURL string
	}{
		Ctx:      ctx,
		QueueURL: queueURL,
	}
	mock.lockQueueItem.Lock()
	mock.calls.QueueItem = append(mock.calls.QueueItem, callInfo)
	mock.lockQueueItem.Unlock()
	return mock.QueueItemFunc(ctx, queueURL)
}

// QueueItemCalls gets all the calls that were made to QueueItem.
// Check the length with:
//
//	len(mockedjenkinsClient.QueueItemCalls())
func (mock *jenkinsClientMock) QueueItemCalls() []struct {
	Ctx      context.Context
	QueueURL string
} {
	var calls []struct {
		Ctx      context.Context
		QueueURL string
	}
	mock.lockQueueItem.RLock()
	calls = mock.calls.QueueItem
	mock.lockQueueItem.RUnlock()
	return calls
}

// StageView calls StageViewFunc.
func (mock *jenkinsClientMock) StageView(ctx context.Context, buildURL string) ([]jenkins.Stage, error) {
	if mock.StageViewFunc == nil {
		panic("jenkinsClientMock.StageViewFunc: method is nil but jenkinsClient.StageView was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BuildURL string
	}{
		Ctx:      ctx,
		BuildURL: buildURL,
	}
	mock.lockStageView.Lock()
	mock.calls.StageView = append(mock.calls.StageView, callInfo)
	mock.lockStageView.Unlock()
	return mock.StageViewFunc(ctx, buildURL)
}

// StageViewCalls gets all the calls that were made to StageView.
// Check the length with:
//
//	len(mockedjenkinsClient.StageViewCalls())
func (mock *jenkinsClientMock) StageViewCalls() []struct {
	Ctx      context.Context
	BuildURL string
} {
	var calls []struct {
		Ctx      context.Context
		BuildURL string
	}
	mock.lockStageView.RLock()
	calls = mock.calls.StageView
	mock.lockStageView.RUnlock()
	return calls
}

// WhoAmI calls WhoAmIFunc.
func (mock *jenkinsClientMock) WhoAmI(ctx context.Context) (jenkins.Identity, error) {
	if mock.WhoAmIFunc == nil {
		panic("jenkinsClientMock.WhoAmIFunc: method is nil but jenkinsClient.WhoAmI was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWhoAmI.Lock()
	mock.calls.WhoAmI = append(mock.calls.WhoAmI, callInfo)
	mock.lockWhoAmI.Unlock()
	return mock.WhoAmIFunc(ctx)
}

// WhoAmICalls gets all the calls that were made to WhoAmI.
// Check the length with:
//
//	len(mockedjenkinsClient.WhoAmICalls())
func (mock *jenkinsClientMock) WhoAmICalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWhoAmI.RLock()
	calls = mock.calls.WhoAmI
	mock.lockWhoAmI.RUnlock()
	return calls
}
