// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq
//
// TODO(jcli): regenerate with `go generate ./internal/agent/` once moq can load this package.
// moq currently fails to load the package on darwin because keychain_darwin.go uses cgo against
// the Security framework (moq's loader does not compile the Objective-C
// preamble). This mock is hand-written to match moq's output shape so a future regeneration is a
// drop-in replacement.

package agent

import (
	"sync"
)

// Ensure, that keychainStoreMock does implement keychainStore.
// If this is not the case, regenerate this file with moq.
var _ keychainStore = &keychainStoreMock{}

// keychainStoreMock is a mock implementation of keychainStore.
type keychainStoreMock struct {
	// SetFunc mocks the Set method.
	SetFunc func(profile string, token string) error

	// GetFunc mocks the Get method.
	GetFunc func(profile string) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(profile string) error

	// calls tracks calls to the methods.
	calls struct {
		// Set holds details about calls to the Set method.
		Set []struct {
			// Profile is the profile argument value.
			Profile string
			// Token is the token argument value.
			Token string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Profile is the profile argument value.
			Profile string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Profile is the profile argument value.
			Profile string
		}
	}
	lockSet    sync.RWMutex
	lockGet    sync.RWMutex
	lockDelete sync.RWMutex
}

// Set calls SetFunc.
func (mock *keychainStoreMock) Set(profile string, token string) error {
	if mock.SetFunc == nil {
		panic("keychainStoreMock.SetFunc: method is nil but keychainStore.Set was just called")
	}
	callInfo := struct {
		Profile string
		Token   string
	}{
		Profile: profile,
		Token:   token,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(profile, token)
}

// SetCalls gets all the calls that were made to Set.
func (mock *keychainStoreMock) SetCalls() []struct {
	Profile string
	Token   string
} {
	mock.lockSet.RLock()
	calls := mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *keychainStoreMock) Get(profile string) (string, error) {
	if mock.GetFunc == nil {
		panic("keychainStoreMock.GetFunc: method is nil but keychainStore.Get was just called")
	}
	callInfo := struct {
		Profile string
	}{
		Profile: profile,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(profile)
}

// GetCalls gets all the calls that were made to Get.
func (mock *keychainStoreMock) GetCalls() []struct {
	Profile string
} {
	mock.lockGet.RLock()
	calls := mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *keychainStoreMock) Delete(profile string) error {
	if mock.DeleteFunc == nil {
		panic("keychainStoreMock.DeleteFunc: method is nil but keychainStore.Delete was just called")
	}
	callInfo := struct {
		Profile string
	}{
		Profile: profile,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(profile)
}

// DeleteCalls gets all the calls that were made to Delete.
func (mock *keychainStoreMock) DeleteCalls() []struct {
	Profile string
} {
	mock.lockDelete.RLock()
	calls := mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}
